use strum_macros::{Display, EnumString};

#[derive(Debug, PartialEq, Display, EnumString)]
#[strum(serialize_all = "lowercase")]
pub enum Kind {
    /// The message is sent in the context of a one-to-one chat conversation.
    Chat,
    /// An error has occurred related to a previous message sent by the sender.
    Error,
    /// The message is sent in the context of a multi-user chat environment.
    Groupchat,
    /// The message is probably generated by an automated service that delivers or
    /// broadcasts content.
    Headline,
    /// The message is a single message that is sent outside the context of a
    /// one-to-one conversation or groupchat, and to which it is expected that the
    /// recipient will reply.
    Normal,
}
