on:
  push:
    tags:
      - "*.*.*"

permissions:
  id-token: write
  contents: write

name: Build and Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust toolchain
        run: rustup toolchain install

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          registry-url: https://registry.npmjs.org

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: latest

      - name: Install git-cliff
        run: cargo install git-cliff

      - name: Verify versions
        run: rustc --version && rustup --version && cargo --version && wasm-pack --version && node --version && npm --version && node -p process.versions.v8

      - name: Cache build context
        id: cache-cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: build-${{ runner.os }}-cargo

      - name: Release SDK (Wasm/JS)
        run: cargo xtask wasm-pack publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
